# Generated by Django 4.0.5 on 2022-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagee',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
